import { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { ChevronLeft } from 'lucide-react-native';
import { getApplication, saveApplication } from '@/lib/database';
import { STATUS_LABELS, STATUSES, type ApplicationInput } from '@/lib/types';
import { useAppColors } from '@/lib/theme';

const empty: ApplicationInput = { company: '', role: '', status: 'saved', source: '', location: '', notes: '' };

export default function EditApplicationScreen() {
  const db = useSQLiteContext(); const router = useRouter(); const params = useLocalSearchParams<{ id?: string }>(); const palette = useAppColors();
  const [form, setForm] = useState<ApplicationInput>(empty); const [saving, setSaving] = useState(false);
  useEffect(() => { if (params.id) getApplication(db, Number(params.id)).then((item) => item && setForm({ company: item.company, role: item.role, status: item.status, source: item.source, location: item.location, notes: item.notes })); }, [db, params.id]);
  const update = <K extends keyof ApplicationInput>(key: K, value: ApplicationInput[K]) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { if (!form.company.trim() || !form.role.trim()) { Alert.alert('Data belum lengkap', 'Isi nama perusahaan dan posisi terlebih dahulu.'); return; } setSaving(true); try { await saveApplication(db, { ...form, company: form.company.trim(), role: form.role.trim() }, params.id ? Number(params.id) : undefined); router.back(); } finally { setSaving(false); } };
  return <ScrollView style={[styles.screen, { backgroundColor: palette.paper }]} contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><ChevronLeft color={palette.ink} size={26} /></Pressable><Text style={[styles.headerTitle, { color: palette.ink }]}>{params.id ? 'Edit lamaran' : 'Lamaran baru'}</Text><View style={{ width: 26 }} /></View><Text style={[styles.label, { color: palette.ink }]}>Perusahaan *</Text><TextInput value={form.company} onChangeText={(v) => update('company', v)} placeholder="Contoh: Nusantara Studio" placeholderTextColor={palette.muted} style={[styles.input, { backgroundColor: palette.surface, borderColor: palette.line, color: palette.ink }]} /><Text style={[styles.label, { color: palette.ink }]}>Posisi *</Text><TextInput value={form.role} onChangeText={(v) => update('role', v)} placeholder="Contoh: Product Designer" placeholderTextColor={palette.muted} style={[styles.input, { backgroundColor: palette.surface, borderColor: palette.line, color: palette.ink }]} /><Text style={[styles.label, { color: palette.ink }]}>Status</Text><View style={styles.statuses}>{STATUSES.map((item) => <Pressable key={item} onPress={() => update('status', item)} style={[styles.status, { backgroundColor: form.status === item ? palette.green : palette.surface, borderColor: palette.line }]}><Text style={{ color: form.status === item ? '#fff' : palette.ink }}>{STATUS_LABELS[item]}</Text></Pressable>)}</View><Text style={[styles.label, { color: palette.ink }]}>Lokasi</Text><TextInput value={form.location} onChangeText={(v) => update('location', v)} placeholder="Remote / Kota" placeholderTextColor={palette.muted} style={[styles.input, { backgroundColor: palette.surface, borderColor: palette.line, color: palette.ink }]} /><Text style={[styles.label, { color: palette.ink }]}>Sumber</Text><TextInput value={form.source} onChangeText={(v) => update('source', v)} placeholder="LinkedIn, referral, website..." placeholderTextColor={palette.muted} style={[styles.input, { backgroundColor: palette.surface, borderColor: palette.line, color: palette.ink }]} /><Text style={[styles.label, { color: palette.ink }]}>Catatan</Text><TextInput value={form.notes} onChangeText={(v) => update('notes', v)} multiline numberOfLines={5} placeholder="Konteks, kontak, atau langkah berikutnya" placeholderTextColor={palette.muted} style={[styles.input, styles.notes, { backgroundColor: palette.surface, borderColor: palette.line, color: palette.ink }]} /><Pressable disabled={saving} onPress={save} style={[styles.save, { backgroundColor: palette.green }]}><Text style={styles.saveText}>{saving ? 'Menyimpan...' : 'Simpan lamaran'}</Text></Pressable></ScrollView>;
}

const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 20, paddingTop: 56, paddingBottom: 44 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 28 }, headerTitle: { fontSize: 18, fontWeight: '700' }, label: { fontSize: 13, fontWeight: '700', marginBottom: 8, marginTop: 16 }, input: { minHeight: 48, borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, fontSize: 15 }, notes: { minHeight: 110, textAlignVertical: 'top', paddingTop: 14 }, statuses: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, status: { borderWidth: 1, borderRadius: 17, paddingVertical: 8, paddingHorizontal: 11 }, save: { minHeight: 52, borderRadius: 15, alignItems: 'center', justifyContent: 'center', marginTop: 28 }, saveText: { color: '#fff', fontWeight: '800', fontSize: 15 } });
