import { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { getCounts } from '@/lib/database';
import { STATUS_LABELS, STATUSES } from '@/lib/types';
import { useAppColors } from '@/lib/theme';

export default function InsightsScreen() { const db = useSQLiteContext(); const palette = useAppColors(); const [counts, setCounts] = useState<Record<string, number>>({}); const refresh = useCallback(async () => setCounts(await getCounts(db)), [db]); useFocusEffect(useCallback(() => { refresh(); }, [refresh])); const total = Object.values(counts).reduce((sum, value) => sum + value, 0); const active = (counts.saved ?? 0) + (counts.applied ?? 0) + (counts.assessment ?? 0) + (counts.interview ?? 0) + (counts.offer ?? 0); return <ScrollView style={[styles.screen, { backgroundColor: palette.paper }]} contentContainerStyle={styles.content}><Text style={[styles.eyebrow, { color: palette.green }]}>INSIGHT</Text><Text style={[styles.title, { color: palette.ink }]}>Baca pola, bukan menebak masa depan.</Text><Text style={[styles.intro, { color: palette.muted }]}>Ringkasan ini dihitung dari data yang kamu simpan di perangkat.</Text><View style={styles.summary}><View style={[styles.bigCard, { backgroundColor: palette.green }]}><Text style={styles.bigNumber}>{total}</Text><Text style={styles.bigLabel}>Total lamaran</Text></View><View style={[styles.bigCard, { backgroundColor: palette.surface, borderColor: palette.line, borderWidth: 1 }]}><Text style={[styles.bigNumber, { color: palette.ink }]}>{active}</Text><Text style={[styles.bigLabel, { color: palette.muted }]}>Masih aktif</Text></View></View><Text style={[styles.section, { color: palette.ink }]}>Distribusi status</Text>{STATUSES.map((status) => <View key={status} style={[styles.row, { borderBottomColor: palette.line }]}><Text style={[styles.rowLabel, { color: palette.ink }]}>{STATUS_LABELS[status]}</Text><Text style={[styles.rowValue, { color: palette.green }]}>{counts[status] ?? 0}</Text></View>)}{total === 0 ? <Text style={[styles.empty, { color: palette.muted }]}>Insight akan muncul setelah kamu menyimpan lamaran pertama.</Text> : null}</ScrollView>; }

const styles = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 20, paddingTop: 64, paddingBottom: 100 }, eyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 2 }, title: { fontSize: 29, lineHeight: 35, fontWeight: '700', marginTop: 9 }, intro: { fontSize: 14, lineHeight: 21, marginTop: 10 }, summary: { flexDirection: 'row', gap: 10, marginTop: 28, marginBottom: 30 }, bigCard: { flex: 1, borderRadius: 18, padding: 18 }, bigNumber: { color: '#fff', fontSize: 32, fontWeight: '800' }, bigLabel: { color: '#DCEBE3', marginTop: 5 }, section: { fontSize: 18, fontWeight: '700', marginBottom: 10 }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 15, borderBottomWidth: 1 }, rowLabel: { fontSize: 15 }, rowValue: { fontSize: 16, fontWeight: '800' }, empty: { textAlign: 'center', marginTop: 30 } });
