import { useCallback, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { Database, FilePlus2, Trash2 } from 'lucide-react-native';
import { clearAllData, seedDemoData } from '@/lib/database';
import { useAppColors } from '@/lib/theme';

export default function SettingsScreen() { const db = useSQLiteContext(); const palette = useAppColors(); const [demoLoaded, setDemoLoaded] = useState(false); const refresh = useCallback(async () => { const row = await db.getFirstAsync<{ value: string }>("SELECT value FROM settings WHERE key = 'demo_data_loaded'"); setDemoLoaded(row?.value === '1'); }, [db]); useFocusEffect(useCallback(() => { refresh(); }, [refresh])); const loadDemo = async () => { const added = await seedDemoData(db); if (added) { setDemoLoaded(true); Alert.alert('Data contoh ditambahkan', 'Kamu bisa mengubah atau menghapusnya kapan saja.'); } else Alert.alert('Data sudah ada', 'Data contoh hanya ditambahkan ketika database masih kosong.'); }; const clear = () => Alert.alert('Hapus semua data?', 'Tindakan ini tidak dapat dibatalkan.', [{ text: 'Batal', style: 'cancel' }, { text: 'Hapus semua', style: 'destructive', onPress: async () => { await clearAllData(db); setDemoLoaded(false); } }]); return <View style={[styles.screen, { backgroundColor: palette.paper }]}><Text style={[styles.eyebrow, { color: palette.green }]}>PENGATURAN</Text><Text style={[styles.title, { color: palette.ink }]}>Data tetap milikmu.</Text><Text style={[styles.intro, { color: palette.muted }]}>Jejak Karier menyimpan data di database SQLite lokal pada perangkat ini. Tidak ada akun atau server yang diperlukan.</Text><View style={[styles.info, { backgroundColor: palette.surface, borderColor: palette.line }]}><Database color={palette.green} size={22} /><View style={{ flex: 1 }}><Text style={[styles.infoTitle, { color: palette.ink }]}>Penyimpanan lokal</Text><Text style={[styles.infoText, { color: palette.muted }]}>Data lamaran hanya tersimpan di perangkat ini.</Text></View></View><Pressable onPress={loadDemo} style={[styles.action, { backgroundColor: palette.surface, borderColor: palette.line }]}><FilePlus2 color={palette.green} size={20} /><Text style={[styles.actionText, { color: palette.ink }]}>{demoLoaded ? 'Data contoh sudah tersedia' : 'Isi data contoh'}</Text></Pressable><Pressable onPress={clear} style={[styles.action, { backgroundColor: palette.surface, borderColor: palette.line }]}><Trash2 color={palette.red} size={20} /><Text style={[styles.actionText, { color: palette.red }]}>Hapus semua data</Text></Pressable><Text style={[styles.version, { color: palette.muted }]}>Jejak Karier · MVP lokal</Text></View>; }

const styles = StyleSheet.create({ screen: { flex: 1, padding: 20, paddingTop: 64 }, eyebrow: { fontSize: 11, fontWeight: '800', letterSpacing: 2 }, title: { fontSize: 30, fontWeight: '700', marginTop: 8 }, intro: { fontSize: 15, lineHeight: 23, marginTop: 12, maxWidth: 350 }, info: { flexDirection: 'row', gap: 14, padding: 16, borderWidth: 1, borderRadius: 16, marginTop: 30 }, infoTitle: { fontSize: 15, fontWeight: '700' }, infoText: { fontSize: 13, lineHeight: 19, marginTop: 4 }, action: { flexDirection: 'row', gap: 12, alignItems: 'center', padding: 17, borderWidth: 1, borderRadius: 15, marginTop: 12 }, actionText: { fontSize: 15, fontWeight: '700' }, version: { textAlign: 'center', marginTop: 32, fontSize: 12 } });
